/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export type types_test = {
  ['/test-simple']: {
    ['GET']: {
      request: null
      response: {status: 200, body: ({
        status: 0 | 1,
        status_shifted: 1 | 2,
        status_text: 'Status 1' | 'Status 2'
      })[]}
    },
    ['POST']: {
      request: {
        status: 0 | 1,
        status_shifted: 1 | 2,
        status_text: 'Status 1' | 'Status 2'
      }
      response: {status: 200, body: {
        /** The status code. */
        statusCode: 200
      }}
    }
  },
  ['/test-simple/{id}']: {
    ['GET']: {
      request: null
      response: {status: 200, body: {
        status: 0 | 1,
        status_shifted: 1 | 2,
        status_text: 'Status 1' | 'Status 2'
      }} | {status: 404, body: {
        /** The status code. */
        statusCode: 404
      }}
    }
  }
};
