/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export enum Status {
  STATUS_1,
  STATUS_2,
}

export enum StatusShifted {
  STATUS_1 = 1,
  STATUS_2 = 2,
}

export enum StatusText {
  STATUS_1 = "Status 1",
  STATUS_2 = "Status 2",
}

export interface TestEnumModel {
  status: Status;
  status_shifted: StatusShifted;
  status_text: StatusText;
}
export function isTestEnumModel(arg: any): arg is TestEnumModel {
  return (
    arg["status"] !== undefined &&
    true &&
    arg["status_shifted"] !== undefined &&
    true &&
    arg["status_text"] !== undefined &&
    true
  );
}
