/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export type types_test = {
  ['/test-simple/widgets']: {
    ['GET']: {
      request: null
      response: {status: 200, body: ({
        id: string,
        status: 'active' | 'inactive',
        details: {
          type: 'small',
          weight: number,
          color: 'red' | 'blue'
        } | {
          type: 'large',
          size: string,
          capacity: number
        },
        tags?: ({
          name: string,
          value: string
        })[]
      })[]} | {status: 200, body: {
        code: number,
        message: string
      }}
    },
    ['POST']: {
      request: {
        status: 'active' | 'inactive',
        details: {
          type: 'small',
          weight: number,
          color: 'red' | 'blue'
        } | {
          type: 'large',
          size: string,
          capacity: number
        },
        tags?: ({
          name: string,
          value: string
        })[]
      }
      response: {status: 200, body: {
        id: string,
        status: 'active' | 'inactive',
        details: {
          type: 'small',
          weight: number,
          color: 'red' | 'blue'
        } | {
          type: 'large',
          size: string,
          capacity: number
        },
        tags?: ({
          name: string,
          value: string
        })[]
      }} | {status: 200, body: {
        code: number,
        message: string
      }}
    }
  },
  ['/test-simple/widgets/{id}']: {
    ['GET']: {
      request: null
      response: {status: 200, body: {
        id: string,
        status: 'active' | 'inactive',
        details: {
          type: 'small',
          weight: number,
          color: 'red' | 'blue'
        } | {
          type: 'large',
          size: string,
          capacity: number
        },
        tags?: ({
          name: string,
          value: string
        })[]
      }} | {status: 200, body: {
        code: number,
        message: string
      }}
    }
  }
};
