/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export enum WidgetSize {
  SMALL = "small",
  LARGE = "large",
}

export enum WidgetStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
}

export type WidgetDetails = SmallWidget | LargeWidget;

export interface Tag {
  name: string;
  value: string;
}
export function isTag(arg: any): arg is Tag {
  return (
    arg["name"] !== undefined &&
    typeof arg["name"] === "string" &&
    arg["value"] !== undefined &&
    typeof arg["value"] === "string"
  );
}

export interface SmallWidget {
  type: WidgetSize.SMALL;
  weight: number;
  color: "red" | "blue";
}
export function isSmallWidget(arg: any): arg is SmallWidget {
  return (
    arg["type"] !== undefined &&
    true &&
    arg["weight"] !== undefined &&
    typeof arg["weight"] === "number" &&
    arg["color"] !== undefined &&
    (typeof arg["color"] === "string" || typeof arg["color"] === "string")
  );
}

export interface LargeWidget {
  type: WidgetSize.LARGE;
  size: string;
  capacity: number;
}
export function isLargeWidget(arg: any): arg is LargeWidget {
  return (
    arg["type"] !== undefined &&
    true &&
    arg["size"] !== undefined &&
    typeof arg["size"] === "string" &&
    arg["capacity"] !== undefined &&
    typeof arg["capacity"] === "number"
  );
}

export interface Widget {
  id: string;
  status: WidgetStatus;
  details: WidgetDetails;
  tags?: Tag[];
}
export function isWidget(arg: any): arg is Widget {
  return (
    (arg["id"] !== undefined &&
      typeof arg["id"] === "string" &&
      arg["status"] !== undefined &&
      true &&
      arg["details"] !== undefined &&
      (isSmallWidget(arg["details"]) || isLargeWidget(arg["details"])) &&
      arg["tags"] === undefined) ||
    (Array.isArray(arg["tags"]) && arg["tags"].every((v) => isTag(v)))
  );
}

export interface Error {
  code: number;
  message: string;
}
export function isError(arg: any): arg is Error {
  return (
    arg["code"] !== undefined &&
    typeof arg["code"] === "number" &&
    arg["message"] !== undefined &&
    typeof arg["message"] === "string"
  );
}
