/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export const routes_test = {
  list: {
    method: "GET",
    path: "/test-simple/widgets",
    getUrl: (): string => `/test-simple/widgets`,
    auth: [null],
  },
  read: {
    method: "GET",
    path: "/test-simple/widgets/{id}",
    getUrl: (params: { id: string }): string =>
      `/test-simple/widgets/${params.id}`,
    auth: [null],
  },
  create: {
    method: "POST",
    path: "/test-simple/widgets",
    getUrl: (): string => `/test-simple/widgets`,
    auth: [null],
  },
} as const;
