/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export interface TestSimpleA {
  id: number,
  name: string
};
export function isTestSimpleA(arg: any): arg is TestSimpleA {
  return (
    arg['id'] !== undefined && (typeof arg['id'] === 'number') &&
    arg['name'] !== undefined && (typeof arg['name'] === 'string')
  );
};

