/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export type types_test = {
  ['/test-simple']: {
    ['GET']: {
      request: null
      response: {status: 200, body: ({
        id: number,
        name: string
      })[]} | {status: 418, body: 'Me teapot'}
    },
    ['POST']: {
      request: {
        name: string
      }
      response: {status: 200, body: {
        /** The status code. */
        statusCode: 200
      }}
    }
  },
  ['/test-simple/{id}']: {
    ['GET']: {
      request: null
      response: {status: 200, body: {
        id: number,
        name: string
      }} | {status: 404, body: {
        /** The status code. */
        statusCode: 404
      }} | {status: 418, body: {
        status: 418
      }} | {status: 419, body: {
      }}
    }
  }
};
