/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export type types_test = {
  ['/test-simple']: {
    ['GET']: {
      request: null
      response: {status: 200, body: ({
        a: boolean,
        b: boolean
      } | number)[]} | {status: 418, body: 'Me teapot'}
    },
    ['POST']: {
      request: {
        a: boolean,
        b: boolean
      } | number
      response: {status: 200, body: {
        a: number | {
          a: boolean,
          b: boolean
        } | number,
        b: boolean | string,
        c: {
          a: boolean,
          b: boolean
        } | number | {
          b: boolean
        } | number
      }}
    }
  }
};
