/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export const routes_test = {
  getAll: {
    method: "GET",
    path: "/test-simple",
    getUrl: (): string => `/test-simple`,
    auth: [null],
  },
  add: {
    method: "POST",
    path: "/test-simple",
    getUrl: (): string => `/test-simple`,
    auth: [null],
  },
} as const;
