/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export type UnionA =
  | {
      a: boolean;
      b: boolean;
    }
  | number;

export type UnionB =
  | {
      a: boolean;
      b: boolean;
    }[]
  | number;

export type UnionVisibility =
  | {
      a: boolean;
      b: boolean;
    }
  | number;

export interface UnionModel {
  a: number | UnionA;
  b: boolean | string;
  c: UnionA | UnionVisibility;
}
export function isUnionModel(arg: any): arg is UnionModel {
  return (
    arg["a"] !== undefined &&
    (typeof arg["a"] === "number" ||
      (arg["a"]["a"] !== undefined &&
        typeof arg["a"]["a"] === "boolean" &&
        arg["a"]["b"] !== undefined &&
        typeof arg["a"]["b"] === "boolean") ||
      typeof arg["a"] === "number") &&
    arg["b"] !== undefined &&
    (typeof arg["b"] === "boolean" || typeof arg["b"] === "string") &&
    arg["c"] !== undefined &&
    ((arg["c"]["a"] !== undefined &&
      typeof arg["c"]["a"] === "boolean" &&
      arg["c"]["b"] !== undefined &&
      typeof arg["c"]["b"] === "boolean") ||
      typeof arg["c"] === "number" ||
      (arg["c"]["a"] !== undefined &&
        typeof arg["c"]["a"] === "boolean" &&
        arg["c"]["b"] !== undefined &&
        typeof arg["c"]["b"] === "boolean") ||
      typeof arg["c"] === "number")
  );
}
