/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export const routes_test = {
  /** List Tests */
  list: {
    method: "GET",
    path: "/test-simple/visibility",
    getUrl: (): string => `/test-simple/visibility`,
    auth: [null],
  },
  read: {
    method: "GET",
    path: "/test-simple/visibility/{id}",
    getUrl: (params: { id: string }): string =>
      `/test-simple/visibility/${params.id}`,
    auth: [null],
  },
  create: {
    method: "POST",
    path: "/test-simple/visibility",
    getUrl: (): string => `/test-simple/visibility`,
    auth: [null],
  },
  update: {
    method: "PATCH",
    path: "/test-simple/visibility/{id}",
    getUrl: (params: { id: string }): string =>
      `/test-simple/visibility/${params.id}`,
    auth: [null],
  },
} as const;
