/* eslint-disable */


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export type types_test = {
  ['/test-simple/visibility']: {
    ['GET']: {
      request: null
      response: {status: 200, body: ({
        name: string,
        display: string,
        always: boolean,
        readCreateModel: {
          always: boolean,
        }
      })[]}
    },
    ['POST']: {
      request: {
        name: string,
        always: boolean,
        readCreateModel: {
          always: boolean,
          create: string
        }
      }
      response: {status: 201, body: {
        name: string,
        display: string,
        always: boolean,
        readCreateModel: {
          always: boolean,
        }
      }}
    }
  },
  ['/test-simple/visibility/{id}']: {
    ['GET']: {
      request: null
      response: {status: 200, body: {
        name: string,
        display: string,
        always: boolean,
        readCreateModel: {
          always: boolean,
        }
      }}
    },
    ['PATCH']: {
      request: {
        always: boolean,
        updated: number,
      }
      response: {status: 201, body: {
        name: string,
        display: string,
        always: boolean,
        readCreateModel: {
          always: boolean,
        }
      }}
    }
  }
};
