/* eslint-disable */

/*
 * This file is automatically generated by typespec-typescript-emitter.
 *
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */

export interface TestVisibilityA {
  name: string;
  display: string;
  always: boolean;
  updated: number;
  readCreateModel: {
    always: boolean;
    create: string;
  };
}
export function isTestVisibilityA(arg: any): arg is TestVisibilityA {
  return (
    arg["name"] !== undefined &&
    typeof arg["name"] === "string" &&
    arg["display"] !== undefined &&
    typeof arg["display"] === "string" &&
    arg["always"] !== undefined &&
    typeof arg["always"] === "boolean" &&
    arg["updated"] !== undefined &&
    typeof arg["updated"] === "number" &&
    arg["readCreateModel"] !== undefined &&
    arg["readCreateModel"]["always"] !== undefined &&
    typeof arg["readCreateModel"]["always"] === "boolean" &&
    arg["readCreateModel"]["create"] !== undefined &&
    typeof arg["readCreateModel"]["create"] === "string"
  );
}
