import {EmitContext, emitFile, resolvePath} from '@typespec/compiler';
import {EmitterOptions} from '../lib.js';

const visibilityHelperFile = `
/* eslint-disable */

/*
  This file is auto-generated by typespec-typescript-emitter and
  contains helpers for accessing lifecycle-visibility-modified
  variants of the emitted types.
*/

export enum Lifecycle {
  Read, Create, Update, Delete, Query,
  None, All
}

export type VisibilityMap<T> = {
  [K in keyof T]?: {
    vis?: readonly Lifecycle[]
    nested?: VisibilityMap<T[K]>
  }
}

export type FilterLifecycle<
  T,
  M extends VisibilityMap<T>,
  Current extends Lifecycle
> = {
  [K in keyof T as (
    Current extends Lifecycle.All
      ? K
      : Current extends Lifecycle.None
        ? never
        : K extends keyof M
          ? M[K] extends { vis?: readonly (infer L)[]; }
            ? (undefined extends M[K]['vis']
              ? K
              : (Current extends L ? K : never)
            )
            : K
          : K
  )]: K extends keyof M
    ? M[K] extends {nested?: infer N}
      ? N extends VisibilityMap<T[K]>
        ? FilterLifecycle<T[K], N, Current>
        : T[K]
      : T[K]
    : T[K]
}
`

export const visibilityHelperFileName = "lifecycleVisibility.ts";

export const emitVisibilityHelperFile = async (context: EmitContext<EmitterOptions>): Promise<void> => {
  await emitFile(context.program, {
    path: resolvePath(context.options['out-dir'], visibilityHelperFileName),
    content: visibilityHelperFile
  });
}