import {EmitContext, emitFile, resolvePath} from '@typespec/compiler';
import {EmitterOptions} from '../lib.js';

const visibilityHelperFile = `
/* eslint-disable */

/*
  This file is auto-generated by typespec-typescript-emitter and
  contains helpers for accessing lifecycle-visibility-modified
  variants of the emitted types.
*/

export enum Lifecycle {
  Read, Create, Update, Delete, Query,
  None, All
}

export type FilterLifecycle<
  T,
  VisibilityMap extends Record<string, Lifecycle[]>,
  Current extends Lifecycle
> = {
  [K in keyof T as (
    Current extends Lifecycle.All
      ? K
      : Current extends Lifecycle.None
        ? never
        : K extends keyof VisibilityMap
            ? (Current extends VisibilityMap[K][number] ? K : never)
            : K
  )]: T[K]
}
`

export const visibilityHelperFileName = "lifecycleVisibility.d.ts";

export const emitVisibilityHelperFile = async (context: EmitContext<EmitterOptions>): Promise<void> => {
  await emitFile(context.program, {
    path: resolvePath(context.options['out-dir'], visibilityHelperFileName),
    content: visibilityHelperFile
  });
}