


/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


export const routes_test = {
  /** Retrieves an instance of the ressource */
  getResource: {
    verb: 'GET',
    path: '/',
    getUrl: (): string => `/`,
    auth: [null]
  },
  /** Creates a resource */
  postResource: {
    verb: 'PUT',
    path: '/',
    getUrl: (): string => `/`,
    auth: [null]
  },
  inner: {
    del: {
      verb: 'DELETE',
      path: '/inner',
      getUrl: (): string => `/inner`,
      auth: [null]
    }
  }
} as const;