
// WARN this file may be broken by auto formatting.
// WARN by default in vscode, save: Ctrl+K , Ctrl+Shift+S
/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


import * as test from './test.ts';
import * as test_inner from './test.inner.ts';

export type types_test = {
  ['/']: {
    /** Retrieves an instance of the ressource */
    ['GET']: {
      request: null,
      response: {status: 200, body: test.Resource}
    },
    /** Creates a resource */
    ['PUT']: {
      request: test.Resource | test_inner.InnerModel,
      response: {status: 200, body: {}}
    }
  },
  ['/inner']: {
    ['DELETE']: {
      request: test_inner.InnerModel | test_inner.InnerModel2,
      response: {status: 200, body: {}} | {status: 401, body: {}}
    }
  }
};