
// WARN this file may be broken by auto formatting.
// WARN by default in vscode, save: Ctrl+K , Ctrl+Shift+S
/*
 * This file is automatically generated by typespec-typescript-emitter.
 * 
 * You should not change or manipulate this file, as it will be overwritten.
 * Instead, change the underlying spec.
 */


import * as test from './test.ts';
import * as test_inner from './test.inner.ts';
import {Lifecycle, FilterLifecycle} from './lifecycleVisibility.ts';

export type types_test<V extends Lifecycle = Lifecycle.All> = {
  ['/']: {
    /** Retrieves an instance of the ressource */
    ['GET']: {
      request: null,
      response: {status: 200, body: test.Resource<V extends Lifecycle.All ? (Lifecycle.Read) : V>}
    },
    /** Creates a resource */
    ['PUT']: {
      request: test.Resource<V extends Lifecycle.All ? (Lifecycle.Create | Lifecycle.Update) : V> | test_inner.InnerModel<V extends Lifecycle.All ? (Lifecycle.Create | Lifecycle.Update) : V>,
      response: {status: 200, body: undefined}
    }
  },
  ['/inner']: {
    ['DELETE']: {
      request: test_inner.InnerModel<V extends Lifecycle.All ? (Lifecycle.Delete) : V> | test_inner.InnerModel2,
      response: {status: 200, body: undefined} | {status: 401, body: undefined}
    }
  }
};